### ISSUE TITLE
Duplicated plugin bug 

### ISSUE THREAD

**Issue by SiDronee** [Team-Silver-Sphere/SquadJS#37]
### Description of Issue
Copied the plugin server status and changed it to display the layers and layer history of the server.
When using the Command !layer 1 to activate the bot it prints out correctly the embed.

When you use the refresh ico under the embed you will see in the refresh time the "server status plugin" then after refreshing it turn back to the layer history plugin "with the correct new data". 

So the bot is somehow linked the 2 plugins together. 

### Squad Information
 * Plugins in Use:  Copy of Server Status
 * SquadJS Version: latest Version
 * Squad Version: Latest Version 

### System Information
 * Operating System: UNIX
 * NodeJS Version: xx
 * Yarn Version: xx

**Comment by Thomas-Smyth** [comment]
I believe this is because the plugin cannot differentiate between the Discord embeds. Ideally, we need to find a way to store hidden information in an embed as this would also allow other features such as the option to add kick reactions to TK Discord logs. I doubt this is possible, so instead, I think it would be smart to create a central store of Discord message IDs to the info used to create them. This store could get quite big to we'd probably want messages to be removed after a certain period of time and for reactions to be removed from messages when the message is removed from the store. This would cause issues for messages we expect to linger around for a while, such as status messages, so it would be good to flag in the store to not delete certain messages. I think this could be quite a bit of work to achieve.

Alternatively, one possibility is to remove support for `!server` commands for regular users and encourage users to have a single channel with a single message that is automatically updated.

**Comment by Thomas-Smyth** [comment]
No longer an issue in v2 as we have reworked the server status plugin so there are no longer refresh emojis.
