### ISSUE TITLE
Admin Broadcast log || Requests

### ISSUE THREAD

**Issue by SiDronee** [Team-Silver-Sphere/SquadJS#38]
The Broadcast Log to discord is a nice feature.
But we have also in battlemetrics some default broadcast messages.

This means that the discord will sent alot of broadcasts into the discord channel. Discord doesn't allow more then 1000 connections aday on a single discordbot token and see's this as a bug. Leading into resetting the token to stop the bot access. 

Is it possible to filter out specific broadcast messages from specific users:  example the BattleMetrics sent command?

**Comment by bumbummen99** [comment]
Information: https://github.com/discord/discord-api-docs/issues/215

**Comment by GonzLife** [comment]
Is it possible to see "who" sent the broadcast?

**Comment by Thomas-Smyth** [comment]
> Is it possible to see "who" sent the broadcast?

No. I looked into it and the logs do say "from ...", but the encoding is broken and the value actually changes between announcements even if it's from the same person. 

For that reason this issue is kinda unsolvable and I can only suggest using two different bots or looking through the item bumbummen99 linked for a possible solution.
