### ISSUE TITLE
discord-round-winner || UNIX

### ISSUE THREAD

**Issue by SiDronee** [Team-Silver-Sphere/SquadJS#71]
### Description of Issue
discord-round-winner is sending an incomplete message to the discord channel

### Errors or Screenshots of Issue
Round Winner
Message
**undefined** won on Tallil Outskirts AAS v1

### Squad Information
 * Plugins in Use:  discord-round-winne
 * SquadJS Version: 1.4.1
 * Squad Version: latest

### System Information
 * Operating System: Unix
 * NodeJS Version:  v14.4.0
 * Yarn Version: 1.22.5

**Comment by IgnisAlienus** [comment]
This is due to the squadlog.log. From what we've been able to tell about how the log works is that if both teams still have tickets then the squadlog.log will have both teams marked as winners. Seems like the Squad code will state that a team is a winner as long as there are still tickets left for that team.  So SquadJS will nullify the results if it detects that two winners were posted.

Here's an example, notice how the times for the posted log are the exact same, SquadJS nullified the results in this case:

[2020.09.14-15.20.07:518][544]LogSquadTrace: [DedicatedServer]ASQGameMode::DetermineMatchWinner(): United States Army won on Skorpo Invasion v1
[2020.09.14-15.20.07:518][544]LogSquadTrace: [DedicatedServer]ASQGameMode::DetermineMatchWinner(): Irregular Militia Forces won on Skorpo Invasion v1

**Comment by Thomas-Smyth** [comment]
> So SquadJS will nullify the results if it detects that two winners were posted.

This is `undefined` though as opposed to `null`, so I'd guess that it's because neither appears in the log. Would need to see the respective logs to confirm this.

**Comment by Thomas-Smyth** [comment]
Logs not supplied, closing.
